services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle" # 热重载配置
    extra_hosts:
      - "host.docker.internal:host-gateway" # 确保 Linux 兼容

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - loki
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command:
      - --config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/var/lib/loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log
      - ./logs:/app/logs
    command:
      - --config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

volumes:
  grafana-data:
  loki-data:
  promtail-data: