global:
  scrape_interval: 15s    # 抓取数据的时间间隔

scrape_configs:
  - job_name: 'demo1'
    static_configs:
      - targets: ['host.docker.internal:2365']

  - job_name: 'demo2'
    static_configs:
      - targets: ['host.docker.internal:3055']